kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: certbot-writer
  namespace: default
subjects:
- kind: ServiceAccount
  name: certbot # Name is case sensitive
  namespace: default
roleRef:
  kind: Role #this must be Role or ClusterRole
  name: cert-writer # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io



