apiVersion: apps/v1
kind: Deployment
metadata:
  name: fs-b-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fs-backend
  template:
    metadata:
      labels:
        app: fs-backend
    spec:
      containers:
      - name: fullstack-backend-container
        image: prcek/fullstack_b:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 4000
          protocol: TCP
        resources:
          limits:
            memory: 256Mi
          requests:
            memory: 128Mi
        env:
        - name: SECRET_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: username

