apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    map $http_upgrade $connection_upgrade {
      default upgrade;
      '' close;
    }
    # Add upstream for letsencrypt job
    upstream certbot {
      server certbot:80 max_fails=0 fail_timeout=1s;
    }

    upstream app-a-service {
      server app-a-service:8080 max_fails=0 fail_timeout=1s;
    }

    server {
      listen 443 ssl;
      listen [::]:443 ssl;
      server_name  do.tsstarlet.net;
      ssl_certificate /etc/nginx/certs/do.tsstarlet.net.crt;
      ssl_certificate_key /etc/nginx/certs/do.tsstarlet.net.key;
      location / {
        add_header Content-Type text/plain;
        return 200 "SSL Test do.tsstarlet.net!";
      }
    }

    server {
      listen 443 ssl;
      listen [::]:443 ssl;
      server_name  www.prcek.io;
      ssl_certificate /etc/nginx/certs/www.prcek.io.crt;
      ssl_certificate_key /etc/nginx/certs/www.prcek.io.key;

      location = /robots.txt {
        add_header  Content-Type  text/plain;
        return 200 "User-agent: *\nDisallow: /\n";
      }

      location / {
        #add_header Content-Type text/plain;
        #return 200 "SSL Test www.prcek.io!";
        proxy_pass http://app-a-service/;
      }
    }

    server {
      listen 80;
      listen [::]:80;
      server_name www.prcek.io;

      location ^~ /.well-known/acme-challenge/ {
        proxy_pass http://certbot/.well-known/acme-challenge/;
      }

      location = /robots.txt {
        add_header  Content-Type  text/plain;
        return 200 "User-agent: *\nDisallow: /\n";
      }

      location / {
        return 301 https://www.prcek.io$request_uri;
      }
 
    }


    server {
      listen 80;
      listen [::]:80;
      server_name  _;
      location / {
        add_header Content-Type text/plain;
        return 200 "Kubernetes + Let's encrypt demo. This should be accessible through https!";
      }
      # Redirect all traffic in /.well-known/ to lets encrypt
      location ^~ /.well-known/acme-challenge/ {
        proxy_pass http://certbot/.well-known/acme-challenge/;
        #proxy_http_version 1.1;
        #proxy_set_header upgrade $http_upgrade;
        #proxy_set_header connection $connection_upgrade;
        #proxy_set_header Host $http_host;
        #proxy_set_header x-forwarded-host $http_host;
        #proxy_set_header x-real-ip $remote_addr;
        #proxy_set_header x-forwarded-for $proxy_add_x_forwarded_for;
        #proxy_set_header x-forwarded-protocol $scheme;
        #proxy_set_header x-forwarded-proto $scheme;
      }
      location /a {
        #proxy_pass  http://app-a-service.default.svc.cluster.local:8080/;
        proxy_pass http://app-a-service/;
      }
      location /b {
        proxy_pass  http://app-b-service.default.svc.cluster.local:8080/;
      }
    }
