apiVersion: v1
kind: Service
metadata:
  name: hello
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  - port: 8081
    protocol: TCP
    targetPort: 443
  selector:
    app: nginx-app-proxy
  type: LoadBalancer
